#! /usr/bin/env sh

# -e: exit on error
# -X: print the command before executing it
set -ex

# install keyd
pacman -S keyd
# copy the config
mkdir -p /etc/keyd/
ln -s ./.config/keyd/ /etc/keyd/
# enable the service
systemctl enable keyd


# compile zoom utility
$CC ./.config/hypr/scripts/zoom.c -O3 -s -o ./.config/hypr/scripts/zoom
