#! /usr/bin/env sh

# -e: exit on error
# -X: print the command before executing it
set -ex

# install keyd
sudo pacman -S keyd --noconfirm
# copy the config
mkdir -p /etc/keyd/
sudo ln -s ./.config/keyd/ /etc/keyd/
# enable the service
sudo systemctl enable keyd


# compile zoom utility
$CC ./.config/hypr/scripts/zoom.c -O3 -s -o ./.config/hypr/scripts/zoom
