preload = ~/.config/hypr/wallpaper.jpg

wallpaper {
	monitor = eDP-1
	path = ~/.config/hypr/wallpaper.jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-1
	path = ~/.config/hypr/wallpaper.jpg
	fit_mode = cover
}


wallpaper {
	monitor = DP-2
	path = ~/.config/hypr/wallpaper.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/.config/hypr/wallpaper.jpg
	fit_mode = cover
}

splash = false
