source = ~/.config/hypr/wm/monitors-and-workspaces.conf

$terminal = kitty
$fileManager = nautilus
$settings = XDG_CURRENT_DESKTOP=GNOME gnome-control-center
$browser = zen-browser
$menu = rofi -show combi

source = ~/.config/hypr/wm/startup-apps.conf
source = ~/.config/hypr/wm/settings.conf
source = ~/.config/hypr/wm/binds.conf
