#! /usr/bin/env sh

read -sp "Enter password: " password

# -e: exit on error
# -x: print the command before executing it
set -ex

# install packages
echo $password | sudo pacman -S git \
	zsh \
	keyd \
  stow \
	neovim \
	sddm \
	hyprland \
	swaybg \
	wezterm \
  nautilus \
	zoxide \
  --noconfirm

echo $password | sudo systemctl enable sddm

# clone dotfiles
DOTFILES_REPO=shreyassanthu77/nvim-config
DOTFILES_DIR=dotfiles
git clone https://github.com/$DOTFILES_REPO $DOTFILES_DIR

# change directory
cd $DOTFILES_DIR

# run setup
./scripts/setup.sh $password
