#! /usr/bin/env sh

# check if password is provided as an argument
password=$1

# prompt for password if not provided
if [ -z $password ]
then
	read -sp "Enter password: " password
fi
set -ex

# install pkgx
curl -Ssf https://pkgx.sh | bash

# install dotfiles
stow .

# refresh font cache
fc-cache -f -v

# keyd setup
mkdir -p /etc/keyd/
echo $password | sudo ln -s ~/.config/keyd /etc/keyd
echo $password | sudo systemctl enable keyd


# compile zoom utility
gcc ./.config/hypr/scripts/zoom.c -O3 -s -o ./.config/hypr/scripts/zoom

reboot
